# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flecha.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import os
from InterfacesPyQt5.interfaz import isNumerical


class Ui_flecha_ui(object):
    os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
    def setupUi(self, flecha_ui, nextUi, data):
        flecha_ui.setObjectName("flecha_ui")
        flecha_ui.resize(399, 280)
        self.centralwidget = QtWidgets.QWidget(flecha_ui)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 381, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.inicio_flecha = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.inicio_flecha.setText("")
        self.inicio_flecha.setObjectName("inicio_flecha")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inicio_flecha)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.anguloFlecha = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.anguloFlecha.setObjectName("anguloFlecha")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.anguloFlecha)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.tipo_flecha = QtWidgets.QComboBox(self.formLayoutWidget)
        self.tipo_flecha.setObjectName("tipo_flecha")
        self.tipo_flecha.addItem("")
        self.tipo_flecha.addItem("")
        self.tipo_flecha.addItem("")
        self.tipo_flecha.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tipo_flecha)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.siguiente = QtWidgets.QPushButton(self.centralwidget)
        self.siguiente.setGeometry(QtCore.QRect(310, 210, 75, 23))
        self.siguiente.setObjectName("siguiente")
        self.atras = QtWidgets.QPushButton(self.centralwidget)
        self.atras.setGeometry(QtCore.QRect(220, 210, 75, 23))
        self.atras.setObjectName("atras")
        flecha_ui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(flecha_ui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 399, 22))
        self.menubar.setObjectName("menubar")
        flecha_ui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(flecha_ui)
        self.statusbar.setObjectName("statusbar")
        flecha_ui.setStatusBar(self.statusbar)

        self.retranslateUi(flecha_ui)
        QtCore.QMetaObject.connectSlotsByName(flecha_ui)

        #Adiciones manuales
        flecha_ui.setWindowIcon(QtGui.QIcon('icon.png'))
        self.siguiente.clicked.connect(lambda: self.clicked_siguiente(flecha_ui,nextUi))
        self.atras.clicked.connect(lambda: self.clicked_atras(flecha_ui,nextUi, data))

    # Método llamado cuando se presiona el botón siguiente
    def clicked_siguiente(self, flecha_ui,nextUi):
        # Se validan los datos, en caso de que estén bien se abre la siguiente interfaz
        if isNumerical(self.inicio_flecha.text()) and isNumerical(self.anguloFlecha.text()):
            flecha_ui.close()
            nextUi[2].show()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Error")
            msg.setText("Rellene todos los campos solicitados con valores numéricos")
            msg.setIcon(QMessageBox.Warning)
            __ = msg.exec_()
    
    # Método llamado cuando se presiona el botón atrás, se cierra la pestaña y se abre la de la interfaz principal
    def clicked_atras(self, flecha_ui,nextUi, data):
        flecha_ui.close()
        if data.diedro.isChecked():
            nextUi[1].show()
        else:
            nextUi[0].show()

    def retranslateUi(self, flecha_ui):
        _translate = QtCore.QCoreApplication.translate
        flecha_ui.setWindowTitle(_translate("flecha_ui", "Foil Tools"))
        self.label_15.setText(_translate("flecha_ui", "Coordenada del eje transversal donde inicia flecha: "))
        self.label_2.setText(_translate("flecha_ui", "Ángulo de la flecha (°):"))
        self.label_3.setText(_translate("flecha_ui", "Tipo de flecha:"))
        self.tipo_flecha.setItemText(0, _translate("flecha_ui", "Ala trapezoidal"))
        self.tipo_flecha.setItemText(1, _translate("flecha_ui", "Borde salida constante"))
        self.tipo_flecha.setItemText(2, _translate("flecha_ui", "Borde entrada constante"))
        self.tipo_flecha.setItemText(3, _translate("flecha_ui", "Cuerda constante"))
        self.label.setText(_translate("flecha_ui", "Opciones de la flecha"))
        self.siguiente.setText(_translate("flecha_ui", "Siguiente"))
        self.atras.setText(_translate("flecha_ui", "Atrás"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    flecha_ui = QtWidgets.QMainWindow()
    ui = Ui_flecha_ui()
    ui.setupUi(flecha_ui, None, None)
    flecha_ui.show()
    sys.exit(app.exec_())
