# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog
import os

input_path = ""

def isNumerical(x):
    try:
        float(x)
    except:
        return False
    return True

class Ui_MainWindow(object):
    os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
    def setupUi(self, MainWindow, nextUi):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(478, 469)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 461, 252))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.path = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.path.setObjectName("path")
        self.horizontalLayout_11.addWidget(self.path)
        self.examinar = QtWidgets.QPushButton(self.formLayoutWidget)
        self.examinar.setObjectName("examinar")
        self.horizontalLayout_11.addWidget(self.examinar)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.eje = QtWidgets.QComboBox(self.formLayoutWidget)
        self.eje.setObjectName("eje")
        self.eje.addItem("")
        self.eje.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.eje)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.plano = QtWidgets.QComboBox(self.formLayoutWidget)
        self.plano.setObjectName("plano")
        self.plano.addItem("")
        self.plano.addItem("")
        self.plano.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.plano)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.cuerda = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.cuerda.setText("")
        self.cuerda.setObjectName("cuerda")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cuerda)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.anguloX = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.anguloX.setObjectName("anguloX")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.anguloX)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.anguloY = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.anguloY.setObjectName("anguloY")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.anguloY)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.anguloZ = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.anguloZ.setObjectName("anguloZ")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.anguloZ)
        self.offsetX = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.offsetX.setObjectName("offsetX")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.offsetX)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.offsetY = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.offsetY.setObjectName("offsetY")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.offsetY)
        self.offsetZ = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.offsetZ.setObjectName("offsetZ")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.offsetZ)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 290, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 320, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.m_curvas = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.m_curvas.setObjectName("m_curvas")
        self.verticalLayout.addWidget(self.m_curvas)
        self.diedro = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.diedro.setObjectName("diedro")
        self.verticalLayout.addWidget(self.diedro)
        self.flecha = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.flecha.setObjectName("flecha")
        self.verticalLayout.addWidget(self.flecha)
        self.siguiente = QtWidgets.QPushButton(self.centralwidget)
        self.siguiente.setGeometry(QtCore.QRect(400, 400, 75, 23))
        self.siguiente.setObjectName("siguiente")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 478, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #Adiciones manuales
        MainWindow.setWindowIcon(QtGui.QIcon('icon.png'))
        self.siguiente.clicked.connect(lambda: self.clicked_siguiente(MainWindow,nextUi))
        self.examinar.clicked.connect(self.choose_input_path)

    def num_inputs_ok(self):
        if isNumerical(self.cuerda.text()) and isNumerical(self.anguloX.text()) and isNumerical(self.anguloY.text()) and isNumerical(self.anguloZ.text()) and isNumerical(self.offsetX.text()) and isNumerical(self.offsetY.text()) and isNumerical(self.offsetZ.text()):
            return True
        return False
    # Método llamado cuando se presiona el botón siguiente
    def clicked_siguiente(self, MainWindow,nextUi):
        # Se validan los datos, en caso de que estén bien se abre la siguiente interfaz
        if self.num_inputs_ok() and os.path.exists(self.path.text()):
            MainWindow.close()
            if self.diedro.isChecked():
                nextUi[0].show()
            elif self.flecha.isChecked() and self.m_curvas.isChecked():
                nextUi[1].show()
            elif self.m_curvas.isChecked():
                nextUi[2].show()
            else:
                nextUi[3].show()
        elif self.num_inputs_ok():
            msg = QMessageBox()
            msg.setWindowTitle("Error")
            msg.setText("El archivo especificado no existe")
            msg.setIcon(QMessageBox.Warning)
            __ = msg.exec_()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Error")
            msg.setText("Rellene todos los campos solicitados")
            msg.setIcon(QMessageBox.Warning)
            __ = msg.exec_()

    # Método llamado cuando se presiona el botón examinar
    def choose_input_path(self):
        global input_path
        # Basado en https://www.youtube.com/watch?v=XgK8ZRvcE5E
        filtro = 'Perfil XFLR5 (*.dat)'
        input_path = QFileDialog.getOpenFileName(None, 'Escoja el archivo del perfil', 'F:\\', filtro)
        #input_path = QtWidgets.QFileDialog.getExistingDirectory(None, 'Escoja el archivo del perfil:', 'F:\\', QtWidgets.QFileDialog.ShowDirsOnly)
        self.path.setText(input_path[0])



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Foil Tools"))
        self.label_12.setText(_translate("MainWindow", "Ubicación del perfil:"))
        self.examinar.setText(_translate("MainWindow", "Examinar"))
        self.label_13.setText(_translate("MainWindow", "Eje sobre el que está el eje longitudinal del avión:"))
        self.eje.setItemText(0, _translate("MainWindow", "Z"))
        self.eje.setItemText(1, _translate("MainWindow", "X"))
        self.label_14.setText(_translate("MainWindow", "Plano sobre el que quiere que se imprima el perfil:"))
        self.plano.setItemText(0, _translate("MainWindow", "Lateral (right)"))
        self.plano.setItemText(1, _translate("MainWindow", "Alzado (front)"))
        self.plano.setItemText(2, _translate("MainWindow", "Planta (top)"))
        self.label_15.setText(_translate("MainWindow", "Dimensión de la cuerda: "))
        self.label_2.setText(_translate("MainWindow", "Ángulo de rotación respecto a eje X (°):"))
        self.label_3.setText(_translate("MainWindow", "Ángulo de rotación respecto a eje Y (°):"))
        self.label_4.setText(_translate("MainWindow", "Ángulo de rotación respecto a eje Z (°):"))
        self.label_5.setText(_translate("MainWindow", "Offset en eje X:"))
        self.label_6.setText(_translate("MainWindow", "Offset en eje Y:"))
        self.label_7.setText(_translate("MainWindow", "Offset en eje Z:"))
        self.label.setText(_translate("MainWindow", "Entradas necesarias"))
        self.label_8.setText(_translate("MainWindow", "Opciones adicionales"))
        self.m_curvas.setText(_translate("MainWindow", "Modo de múltiples curvas"))
        self.diedro.setText(_translate("MainWindow", "Diedro"))
        self.flecha.setText(_translate("MainWindow", "Flecha"))
        self.siguiente.setText(_translate("MainWindow", "Siguiente"))
        self.anguloX.setText(_translate("MainWindow", "0"))
        self.anguloY.setText(_translate("MainWindow", "0"))
        self.anguloZ.setText(_translate("MainWindow", "0"))
        self.offsetX.setText(_translate("MainWindow", "0"))
        self.offsetY.setText(_translate("MainWindow", "0"))
        self.offsetZ.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow, None)
    MainWindow.show()
    sys.exit(app.exec_())
