# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'm_curvas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import os
from InterfacesPyQt5.interfaz import isNumerical


class Ui_m_curvas(object):
    os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
    def setupUi(self, m_curvas, nextUi, data):
        m_curvas.setObjectName("m_curvas")
        m_curvas.resize(399, 281)
        self.centralwidget = QtWidgets.QWidget(m_curvas)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 381, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.fin_ala = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fin_ala.setText("")
        self.fin_ala.setObjectName("fin_ala")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fin_ala)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.num_curvas = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.num_curvas.setObjectName("num_curvas")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.num_curvas)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.siguiente = QtWidgets.QPushButton(self.centralwidget)
        self.siguiente.setGeometry(QtCore.QRect(310, 210, 75, 23))
        self.siguiente.setObjectName("siguiente")
        self.atras = QtWidgets.QPushButton(self.centralwidget)
        self.atras.setGeometry(QtCore.QRect(220, 210, 75, 23))
        self.atras.setObjectName("atras")
        m_curvas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(m_curvas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 399, 22))
        self.menubar.setObjectName("menubar")
        m_curvas.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(m_curvas)
        self.statusbar.setObjectName("statusbar")
        m_curvas.setStatusBar(self.statusbar)

        self.retranslateUi(m_curvas)
        QtCore.QMetaObject.connectSlotsByName(m_curvas)

        #Adiciones manuales
        m_curvas.setWindowIcon(QtGui.QIcon('icon.png'))
        self.siguiente.clicked.connect(lambda: self.clicked_siguiente(m_curvas,nextUi))
        self.atras.clicked.connect(lambda: self.clicked_atras(m_curvas,nextUi, data))

    # Método llamado cuando se presiona el botón siguiente
    def clicked_siguiente(self, m_curvas,nextUi):
        # Se validan los datos, en caso de que estén bien se abre la siguiente interfaz
        if isNumerical(self.fin_ala.text()) and self.num_curvas.value()>1:
            m_curvas.close()
            nextUi[3].show()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Error")
            msg.setText("Rellene todos los campos solicitados con valores numéricos")
            msg.setIcon(QMessageBox.Warning)
            __ = msg.exec_()
    
    # Método llamado cuando se presiona el botón atrás, se cierra la pestaña y se abre la de la interfaz principal
    def clicked_atras(self, m_curvas,nextUi, data):
        m_curvas.close()
        if data.flecha.isChecked():
            nextUi[2].show()
        elif data.diedro.isChecked():
            nextUi[1].show()
        else:
            nextUi[0].show()

    def retranslateUi(self, m_curvas):
        _translate = QtCore.QCoreApplication.translate
        m_curvas.setWindowTitle(_translate("m_curvas", "Foil Tools"))
        self.label_15.setText(_translate("m_curvas", "Coordenada del eje transversal donde termina ala: "))
        self.label_2.setText(_translate("m_curvas", "Número de curvas por generar:"))
        self.label.setText(_translate("m_curvas", "Opciones del modo de múltiples curvas"))
        self.siguiente.setText(_translate("m_curvas", "Siguiente"))
        self.atras.setText(_translate("m_curvas", "Atrás"))
        self.num_curvas.setValue(2)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    m_curvas = QtWidgets.QMainWindow()
    ui = Ui_m_curvas()
    ui.setupUi(m_curvas)
    m_curvas.show()
    sys.exit(app.exec_())
